"""init schema

Revision ID: 3fa899bebd94
Revises: 
Create Date: 2026-08-27 20:15:47.021549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3fa899bebd94'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=255), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('base_url', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('emailVerified', sa.Boolean(), nullable=False),
    sa.Column('image', sa.Text(), nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('verification',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('identifier', sa.Text(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('expiresAt', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updatedAt', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('account',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('accountId', sa.String(), nullable=False),
    sa.Column('providerId', sa.String(), nullable=False),
    sa.Column('userId', sa.String(), nullable=False),
    sa.Column('accessToken', sa.Text(), nullable=True),
    sa.Column('refreshToken', sa.Text(), nullable=True),
    sa.Column('idToken', sa.Text(), nullable=True),
    sa.Column('expiresAt', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('password', sa.Text(), nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('default_branch', sa.String(length=255), nullable=True),
    sa.Column('language_hint', sa.String(length=255), nullable=True),
    sa.Column('github_install_id', sa.Integer(), nullable=True),
    sa.Column('active_model_config_id', sa.UUID(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['active_model_config_id'], ['model_configs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner', 'name', name='uq_repo_owner_name')
    )
    op.create_table('session',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('userId', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('expiresAt', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('ipAddress', sa.String(), nullable=True),
    sa.Column('userAgent', sa.Text(), nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repo_id', sa.UUID(), nullable=False),
    sa.Column('github_run_id', sa.Integer(), nullable=False),
    sa.Column('head_sha', sa.String(length=40), nullable=False),
    sa.Column('head_branch', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('conclusion', sa.String(length=50), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_runs_github_run_id'), 'runs', ['github_run_id'], unique=True)
    op.create_index(op.f('ix_runs_repo_id'), 'runs', ['repo_id'], unique=False)
    op.create_table('attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('patch_text', sa.Text(), nullable=False),
    sa.Column('confidence_score', sa.Integer(), nullable=True),
    sa.Column('strategy_notes', sa.Text(), nullable=True),
    sa.Column('verification_status', sa.String(length=50), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('build_duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attempts_run_id'), 'attempts', ['run_id'], unique=False)
    op.create_table('eval_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=True),
    sa.Column('overall_accuracy', sa.Float(), nullable=True),
    sa.Column('per_subagent_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('model_config_id', sa.UUID(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['model_config_id'], ['model_configs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id')
    )
    op.create_table('run_steps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('step_name', sa.String(length=255), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('cost_estimate', sa.Float(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_run_steps_run_id'), 'run_steps', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_run_steps_run_id'), table_name='run_steps')
    op.drop_table('run_steps')
    op.drop_table('eval_results')
    op.drop_index(op.f('ix_attempts_run_id'), table_name='attempts')
    op.drop_table('attempts')
    op.drop_index(op.f('ix_runs_repo_id'), table_name='runs')
    op.drop_index(op.f('ix_runs_github_run_id'), table_name='runs')
    op.drop_table('runs')
    op.drop_table('session')
    op.drop_table('repos')
    op.drop_table('account')
    op.drop_table('verification')
    op.drop_table('user')
    op.drop_table('model_configs')
    # ### end Alembic commands ###
